### ISSUE TITLE
Fresh download of example app crashes when page is opened

### ISSUE THREAD

**Issue by NZTimKeegan** [playframework/play-java-starter-example#65]
### Steps to reproduce:
1. Download example application (source: https://example.lightbend.com/v1/download/play-java-starter-example)
2. Start application with command `./sbt run`

#### Console output:
```
./sbt run
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/184611/Documents/Play/play-java-starter-example/project
[info] Loading settings from build.sbt ...
[info] Set current project to play-java-starter-example (in build file:/Users/184611/Documents/Play/play-java-starter-example/)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by play.runsupport.classloader.DelegatingClassLoader (file:/Users/184611/.ivy2/cache/com.typesafe.play/run-support_2.12/jars/run-support_2.12-2.6.12.jar) to method java.lang.ClassLoader.findResource(java.lang.String)
WARNING: Please consider reporting this to the maintainers of play.runsupport.classloader.DelegatingClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] application - ApplicationTimer demo: Starting application at 2018-04-05T01:04:25.098849Z
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    filters.ExampleFilter

[info] play.api.Play - Application started (Dev)
Uncaught error from thread [application-akka.actor.default-dispatcher-4]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Uncaught error from thread [application-akka.actor.default-dispatcher-2]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[applicationapplication]
]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:413)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:95)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:297)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Result.bakeCookies(Results.scala:296)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:225)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$5(AkkaHttpServer.scala:323)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 31 more
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:413)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:95)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:297)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Result.bakeCookies(Results.scala:296)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:225)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$5(AkkaHttpServer.scala:323)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-4]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-2]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
  1 name := """play-java-starter-example"""
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
[INFO] [04/05/2018 13:04:25.809] [Thread-1] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

#### Workaround
Add the following to the `build.sbt` file:
```
libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.1"
```
Disclaimer: I am just getting into Java development, and am unsure whether this is the right way to solve this problem. Adding this line to the file appears to solve the issue.

#### Java version
```
> java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

**Comment by wsargent** [comment]
You must run Play on Java 1.8.  It does not work on 9 or 10 yet.

**Comment by marcospereira** [comment]
It is possible to make it work, as described here:

https://groups.google.com/forum/#!topic/play-framework/e3KLg94j5_M

But Java 9 support needs some additional work (see https://github.com/playframework/playframework/issues/7879).

**Comment by marcospereira** [comment]
Closing. It works without adding a parameter since 2.6.16.
